version: 2
jobs:
  build:
    docker:
      # - image: circleci/python:3.4.9
      - image: google/cloud-sdk:latest # to get Python3
    environment:
      TRAIN_DATA:gs://$GOOGLE_BUCKET_NAME/Data
      EVAL_DATA:gs://$GOOGLE_BUCKET_NAME/Data
      RUNTIME_VERSION:1.4
      PYTHON_VERSION:3.5
      now:$(date +"%Y%m%d_%H%M%S")
      JOB_NAME:stock_advisor_$now
      OUTPUT_PATH:gs://$GOOGLE_BUCKET_NAME/$JOB_NAME
      TRAINER_PACKAGE_PATH:"trainer/"
      MAIN_TRAINER_MODULE:"trainer.task"
      PACKAGE_STAGING_PATH:"gs://$GOOGLE_BUCKET_NAME"
      MODEL_DIR:"pred_output/run_20190326-145225"
    steps:
      - checkout
      - run:
          name: "Run training locally"
          command:
            gcloud ml-engine local train --module-name trainer.task --package-path trainer/ --job-dir $MODEL_DIR --
            --train-files $TRAIN_DATA/aapl.us.txt --eval-files $EVAL_DATA/aapl.us.txt --num-epochs 1 --num-samples 10

      # - run:Ë˜
          # name: "Run a training job on the cloud"
          # command:
          #   gcloud ml-engine jobs submit training $JOB_NAME \
          #   --staging-bucket $PACKAGE_STAGING_PATH \
          #   --job-dir $OUTPUT_PATH  \
          #   --package-path $TRAINER_PACKAGE_PATH \
          #   --module-name $MAIN_TRAINER_MODULE \
          #   --python-version $PYTHON_VERSION \
          #   --region $REGION \
          #   --runtime-version $RUNTIME_VERSION \
          #   -- \
          #   --train-files $TRAIN_DATA/aapl.us.txt \
          #   --eval-files $EVAL_DATA/aapl.us.txt \
          #   --num-epochs 10
          #   --num-samples 10
